### ISSUE TITLE
Error Fitur Sticker & Tiktok ( Repl.it )

### ISSUE THREAD

**Issue by sn0wflakes** [Adiixyz/AdyyBOTZ#1]
Problem Pertama Ketika Mau Start Terminal Muncul : 
```
`> ADYYBOTZ@0.0.1 start /home/runner/AdyyBOTZ
> node run

/home/runner/AdyyBOTZ/node_modules/tiktok-scraper-without-watermark/src/function/index.js:209
                    nowm: $('#results-list > div:nth-child(2) > div.download > a')?.attr('href'),
                                                                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
 npm start`
```
Kemudian Setelah const tik = require('tiktok-scraper-without-watermark') dihapus sudah bisa scan & login normal
Namun ketika mencoba menggunakan fitur sticker 
muncul error : `Message : TypeError: Cannot read property 'stanzaId' of null`

Mohon Bantuannya, terimakasih :D

**Comment by Adiixyz** [comment]
yang `Message : TypeError: Cannot read property 'stanzaId' of null` gk ada ap ap

sticker nanti ku fix
